### PR TITLE
mac is bad

### PR DESCRIPTION
**Pull request by sylv256**
fucking useless piece of shit

### CODE REVIEW

**Comment by sylv256** [comment]
it's honestly sad that macs are turing complete
fuck steve jobs

**Review by hYdos — APPROVED** [review]
approv

**Comment by BluCobalt** [comment]
Man died 9 years ago let him rest in peace lol

**Comment by BoogieMonster1O1** [comment]
@hYdos WAIT FOR ME TO APPROVE

**Comment by sylv256** [comment]
@BoogieMonster1O1 calm down you ave too much power

**Comment by hYdos** [comment]
> 
> 
> @hYdos WAIT FOR ME TO APPROVE

calm down it was just mac support

**Pull request merged**
